name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0, v2.1.4, etc.
  #release:
  #  types: [created]
  #  types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write # Release create/edit
  packages: none
  issues: none
  pull-requests: none

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test --configuration Release --no-build

    - name: Parse version from tag
      id: parse_version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "VERSION=$VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Pack NuGet Package
      run: dotnet pack -p:Version=${{ steps.parse_version.outputs.version }} --configuration Release --no-build --output dist WslcWrapper/WslcWrapper.csproj
      
    - name: NuGet Trusted Publishing Login
      uses: NuGet/login@v1
      id: nuget_login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Push to NuGet.org via OIDC
      run: |
        dotnet nuget push "dist/*.nupkg" \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ steps.nuget_login.outputs.NUGET_API_KEY }} \
          --skip-duplicate
    - name: Create GitHub Release with NuGet URL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo -e "### NuGet Packages\n📦 [SilentOrbit.WSLC](https://www.nuget.org/packages/SilentOrbit.WSLC/${{ steps.parse_version.outputs.version }})" > notes.txt

        gh release create ${{ github.ref_name }} \
          --title "${{ github.ref_name }}" \
          --generate-notes \
          --notes-file notes.txt
