name: Publish NuGet Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write # Release edit
  packages: none
  issues: none
  pull-requests: none

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test --configuration Release --no-build

    - name: Parse version from tag
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Pack NuGet Package
      run: dotnet pack -p:Version=$VERSION --configuration Release --no-build --output dist WslcWrapper/WslcWrapper.csproj
      
    - name: NuGet Trusted Publishing Login
      uses: NuGet/login@v1
      id: nuget_login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Push to NuGet.org via OIDC
      run: |
        dotnet nuget push "dist/*.nupkg" \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ steps.nuget_login.outputs.NUGET_API_KEY }} \
          --skip-duplicate
    - name: Update GitHub Release with NuGet URL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release view ${{ github.ref_name }} --json body --template '{{.body}}' > existing_notes.txt
        echo -e "\n\n### NuGet Packages\n📦 [SilentOrbit.WSLC](https://www.nuget.org/packages/SilentOrbit.WSLC/$VERSION)" >> existing_notes.txt
        gh release edit ${{ github.ref_name }} \
          --notes-file existing_notes.txt